version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prerelease
    image: notion-github-integration
    restart: unless-stopped
    command: sh -c "bun install && bun start"
    volumes:
      - ./:/usr/src/app
